package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * GadgetPublish generated by hbm2java
 */
public class GadgetPublish implements java.io.Serializable {

	private Long gadgetId;
	private Date requestedDate;
	private boolean isApproved;
	private String rejectReason;
	private Gadget gadget;

	public GadgetPublish() {
	}

//	public GadgetPublish(Long gadgetId, Date requestedDate,
//			boolean isApproved, String rejectReason) {
//		this.gadgetId = gadgetId;
//		this.requestedDate = requestedDate;
//		this.isApproved = isApproved;
//		this.rejectReason = rejectReason;
//	}

	public Long getGadgetId() {
		return this.gadgetId;
	}

	private void setGadgetId(Long gadgetId) {
		this.gadgetId = gadgetId;
	}

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	public boolean isApproved(){
		return isIsApproved();
	}
	
	private boolean isIsApproved() {
		return this.isApproved;
	}

	public void setApprove(boolean isApproved){
		setIsApproved(isApproved);
	}
	private void setIsApproved(boolean isApproved) {
		this.isApproved = isApproved;
	}

	public String getRejectReason() {
		return this.rejectReason;
	}

	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason;
	}

	public Gadget getGadget() {
		return gadget;
	}

	public void setGadget(Gadget gadget) {
		this.gadget = gadget;
	}
	
	

}
