package com.skt.opensocial.persistence;

// Generated Jun 27, 2009 9:49:44 PM by Hibernate Tools 3.2.4.GA

/**
 * Address generated by hbm2java
 */
public class GroupCategory implements java.io.Serializable {

	private Integer id;
	private String groupName;

	
	public GroupCategory(String groupName) {
		this.groupName = groupName;
	}


	public Integer getId() {
		return this.id;
	}

	private void setId(Integer id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
