package com.skt.opensocial.persistence;

// Generated Jun 27, 2009 9:49:44 PM by Hibernate Tools 3.2.4.GA

/**
 * Address generated by hbm2java
 */
public class GroupCategory implements java.io.Serializable {

	private int id;
	private String groupName;
	private String userId;

	
	public GroupCategory() {

	}


	public int getId() {
		return this.id;
	}

	private void setId(int id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
