package com.skt.opensocial.persistence;

// Generated Jun 27, 2009 9:49:44 PM by Hibernate Tools 3.2.4.GA

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer id;
//	private String userId;
	private String country;
	private Double latitude;
	private Double longitude;
	private String locality;
	private String postalCode;
	private String region;
	private String streetAddress;
	private String type;
	private String formatted;
	private Boolean primary;
	private Person person;

	public Address() {
	}

//	public Address(String userId, String country, Double latitude,
//			Double longitude, String locality, String postalCode,
//			String region, String streetAddress, String type, String formatted,
//			Boolean primary) {
//		this.userId = userId;
//		this.country = country;
//		this.latitude = latitude;
//		this.longitude = longitude;
//		this.locality = locality;
//		this.postalCode = postalCode;
//		this.region = region;
//		this.streetAddress = streetAddress;
//		this.type = type;
//		this.formatted = formatted;
//		this.primary = primary;
//	}

	public Integer getId() {
		return this.id;
	}

	private void setId(Integer id) {
		this.id = id;
	}
//
//	public String getUserId() {
//		return this.userId;
//	}
//
//	public void setUserId(String userId) {
//		this.userId = userId;
//	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getFormatted() {
		return this.formatted;
	}

	public void setFormatted(String formatted) {
		this.formatted = formatted;
	}

	public Boolean getPrimary() {
		return this.primary;
	}

	public void setPrimary(Boolean primary) {
		this.primary = primary;
	}

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
