package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gadget generated by hbm2java
 */
public class Gadget implements java.io.Serializable {

	private Long id;
	private String name;
	private Date registerDate;
	private Date publishDate;
	private String status;
	private String registerType;
	private String introduction;
	private String source;
	private String iconUrl;
	// private String developerId;
	private User developer;
	private Set<GadgetCategory> categories;
	private Set<GadgetReview> reviews;
	private Set<User> favoriteUsers = new HashSet<User>();
	private GadgetPublish gadgetPublish;

	public Gadget() {
	}

	// public Gadget(String name, String developerId) {
	// this.name = name;
	// this.developerId = developerId;
	// }

	// public Gadget(String name, Date registerDate, Date publishDate,
	// String status, String registerType, String introduction,
	// String source, String iconUrl, String developerId) {
	// this.name = name;
	// this.registerDate = registerDate;
	// this.publishDate = publishDate;
	// this.status = status;
	// this.registerType = registerType;
	// this.introduction = introduction;
	// this.source = source;
	// this.iconUrl = iconUrl;
	// this.developerId = developerId;
	// }

	public Long getId() {
		return this.id;
	}

	private void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRegisterType() {
		return this.registerType;
	}

	public void setRegisterType(String registerType) {
		this.registerType = registerType;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getIconUrl() {
		return this.iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}

	// public String getDeveloperId() {
	// return this.developerId;
	// }
	//
	// public void setDeveloperId(String developerId) {
	// this.developerId = developerId;
	// }

	public User getDeveloper() {
		return developer;
	}

	public void setDeveloper(User developer) {
		this.developer = developer;
	}

	public Set<GadgetCategory> getCategories() {
		return categories;
	}

	public void setCategories(Set<GadgetCategory> categories) {
		this.categories = categories;
	}

	public void addCategory(GadgetCategory category) {

		Set<GadgetCategory> set = getCategories();
		if (set == null)
			set = new HashSet<GadgetCategory>();
		set.add(category);
		setCategories(set);

	}

	public Set<GadgetReview> getReviews() {
		return reviews;
	}

	public void setReviews(Set<GadgetReview> reviews) {
		this.reviews = reviews;
	}

	public void addReview(GadgetReview review) {
		Set<GadgetReview> set = getReviews();
		if (set == null)
			set = new HashSet<GadgetReview>();
		set.add(review);
		setReviews(set);
	}

	public Set<User> getFavoriteUsers() {
		return favoriteUsers;
	}

	public void setFavoriteUsers(Set<User> favoriteUsers) {
		this.favoriteUsers = favoriteUsers;
	}

	public GadgetPublish getGadgetPublish() {
		return gadgetPublish;
	}

	public void setGadgetPublish(GadgetPublish gadgetPublish) {
		this.gadgetPublish = gadgetPublish;
	}

}
