package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * GadgetReview generated by hbm2java
 */
public class GadgetReview implements java.io.Serializable {

	private Long id;
	//private long gadgetId;
	//private String userId;
	private String reviewText;
	private int reviewGrade;
	private Date reviewDate;
	private User reviewer;
	private Gadget gadget;

	public GadgetReview() {
	}

//	public GadgetReview(long gadgetId, String userId, String reviewText,
//			int reviewGrade, Date reviewDate) {
//		this.gadgetId = gadgetId;
//		this.userId = userId;
//		this.reviewText = reviewText;
//		this.reviewGrade = reviewGrade;
//		this.reviewDate = reviewDate;
//	}
	
	public GadgetReview(User user) {
		this.reviewer = user;
		//this.gadget = gadget;
	}
	public GadgetReview(User user, Gadget gadget) {
		this.reviewer = user;
		this.gadget = gadget;
	}

	public Long getId() {
		return this.id;
	}

	private void setId(Long id) {
		this.id = id;
	}

//	public long getGadgetId() {
//		return this.gadgetId;
//	}
//
//	public void setGadgetId(long gadgetId) {
//		this.gadgetId = gadgetId;
//	}

//	public String getUserId() {
//		return this.userId;
//	}
//
//	public void setUserId(String userId) {
//		this.userId = userId;
//	}

	public String getReviewText() {
		return this.reviewText;
	}

	public void setReviewText(String reviewText) {
		this.reviewText = reviewText;
	}

	public int getReviewGrade() {
		return this.reviewGrade;
	}

	public void setReviewGrade(int reviewGrade) {
		this.reviewGrade = reviewGrade;
	}

	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	public User getReviewer() {
		return reviewer;
	}

	public void setReviewer(User reviewer) {
		this.reviewer = reviewer;
	}

	public Gadget getGadget() {
		return gadget;
	}

	public void setGadget(Gadget gadget) {
		this.gadget = gadget;
	}

	
}
