package com.skt.opensocial.persistence;

import java.util.Set;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * PersonAdditionalInfo2 generated by hbm2java
 */
public class PersonAdditionalInfo2 implements java.io.Serializable {

	private Integer id;
	// private String userId;
	private Info2AttributeEnum attribute;
	private String type;
	private String value;
	private Boolean primary;
	private Person person;

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public PersonAdditionalInfo2() {
	}

	/*
	 * public PersonAdditionalInfo2(String userId) { this.userId = userId; }
	 * 
	 * public PersonAdditionalInfo2(String userId, String attribute, String
	 * type, String value, Boolean primary) { this.userId = userId;
	 * this.attribute = attribute; this.type = type; this.value = value;
	 * this.primary = primary; }
	 */

	public Integer getId() {
		return this.id;
	}

	private void setId(Integer id) {
		this.id = id;
	}

	/*
	 * public String getUserId() { return this.userId; }
	 * 
	 * public void setUserId(String userId) { this.userId = userId; }
	 */
	public Info2AttributeEnum getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Info2AttributeEnum attribute) {
		this.attribute = attribute;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Boolean getPrimary() {
		return this.primary;
	}

	public void setPrimary(Boolean primary) {
		this.primary = primary;
	}

}
