package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * PersonAppData generated by hbm2java
 */
public class PersonAppData implements java.io.Serializable {

	private Integer id;
	// private String userId;
	private String appId;
	private String field;
	private String data;
	private Person person;

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public PersonAppData() {
	}

	// public PersonAppData(String userId, String appId, String field, String
	// data) {
	// this.userId = userId;
	// this.appId = appId;
	// this.field = field;
	// this.data = data;
	// }

	public Integer getId() {
		return this.id;
	}

	private void setId(Integer id) {
		this.id = id;
	}

	// public String getUserId() {
	// return this.userId;
	// }
	//
	// public void setUserId(String userId) {
	// this.userId = userId;
	// }

	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
