package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String id;
	private boolean isDeveloper;
	private boolean isAdministrator;
	private String password;
	private Date registeredDate;
	private Person person;
	private UserVisibility userVisibility;
	private Set<GadgetReview> reviews;
	private Set<Gadget> gadgets;// = new HashSet<Gadget>();
	private Set<Gadget> favoriteGadgets;
	private Set<User> friends = new HashSet<User>();

	public User() {
	}

	public User(String id, boolean isDeveloper, boolean isAdministrator,
			String password, Date registeredDate) {
		this.id = id;
		this.isDeveloper = isDeveloper;
		this.isAdministrator = isAdministrator;
		this.password = password;
		this.registeredDate = registeredDate;
	}

	public String getId() {
		return this.id;
	}
	public String getUserId(){
		return getId();
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public void setUserid(String id){
		setId(id);
	}
	public boolean isIsDeveloper() {
		return this.isDeveloper;
	}

	public void setIsDeveloper(boolean isDeveloper) {
		this.isDeveloper = isDeveloper;
	}

	public boolean isIsAdministrator() {
		return this.isAdministrator;
	}

	public void setIsAdministrator(boolean isAdministrator) {
		this.isAdministrator = isAdministrator;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegisteredDate() {
		return this.registeredDate;
	}

	public void setRegisteredDate(Date registeredDate) {
		this.registeredDate = registeredDate;
	}

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public UserVisibility getUserVisibility() {
		return userVisibility;
	}

	public void setUserVisibility(UserVisibility userVisibility) {
		this.userVisibility = userVisibility;
	}

	public Set<GadgetReview> getReviews() {
		return reviews;
	}

	public void setReviews(Set<GadgetReview> reviews) {
		this.reviews = reviews;
	}

	public Set<Gadget> getGadgets() {
		return gadgets;
	}

	public void setGadgets(Set<Gadget> gadgets) {
		this.gadgets = gadgets;
	}
	
	public void addGadget(Gadget gadget) {
		Set<Gadget> gadgets = getGadgets();
//		if(gadgets == null)
//			gadgets = new HashSet<Gadget>();
		gadgets.add(gadget);
		setGadgets(gadgets);
	}
	
	public void removeGadget(Gadget gadget){
		this.getGadgets().remove(gadget);
	}
	

	public Set<Gadget> getFavoriteGadgets() {
		return favoriteGadgets;
	}

	public void setFavoriteGadgets(Set<Gadget> favoriteGadgets) {
		this.favoriteGadgets = favoriteGadgets;
	}
	
	public void addFavoriteGadget(Gadget gadget) {
		this.favoriteGadgets.add(gadget);
	}
	
	public void removeFavoriteGadget(Gadget gadget) {
		this.favoriteGadgets.remove(gadget);
	}
	
	/*public void addFavoriteGadget(Gadget gadget) {
		Set<Gadget> gadgets = getFavoriteGadgets();
		if(gadgets == null)
			gadgets = new HashSet<Gadget>();
		gadgets.add(gadget);
		setFavoriteGadgets(gadgets);
	}*/

	public Set<User> getFriends() {
		return friends;
	}

	public void setFriends(Set<User> friends) {
		this.friends = friends;
	}
	
	public void addFriend(User friend) {
		Set<User> friends = getFriends();
//		if(friends == null)
//			friends = new HashSet<User>();
		friends.add(friend);
		setFriends(friends);
	}
	

}
