package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.Set;

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	//private ActivityKey activityKey;
	private Integer id;
	private String appId;
	private String body;
	private String bodyId;
	private String externalId;
	private String activityId;
	private Date updated;
	private Double postedTime;
	private Double priority;
	private String streamFaviconUrl;
	private String streamSourceUrl;
	private String streamTitle;
	private String streamUrl;
	private String title;
	private String titleId;
	private String url;
	private String userId;
	private Person person;
//	private Set<ActivityMediaItem> mediaItems;
//	private Set<ActivityTemplateParam> templateParams;

	public Activity() {
	}

	

//	public Activity(String appId, String body, String bodyId,
//			String externalId, String activityId, Date updated,
//			Double postedTime, Double priority, String streamFaviconUrl,
//			String streamSourceUrl, String streamTitle, String streamUrl,
//			//String title, String titleId, String url, String userId) {
//			String title, String titleId, String url, Person person) {
//		this.appId = appId;
//		this.body = body;
//		this.bodyId = bodyId;
//		this.externalId = externalId;
//		this.activityId = activityId;
//		this.updated = updated;
//		this.postedTime = postedTime;
//		this.priority = priority;
//		this.streamFaviconUrl = streamFaviconUrl;
//		this.streamSourceUrl = streamSourceUrl;
//		this.streamTitle = streamTitle;
//		this.streamUrl = streamUrl;
//		this.title = title;
//		this.titleId = titleId;
//		this.url = url;
//		//this.userId = userId;
//	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	public ActivityKey getActivityId() {
//		return activityId;
//	}
//
//
//
//	public void setActivityId(ActivityKey activityId) {
//		this.activityId = activityId;
//	}



//	public String getActivityId() {
//		return activityId;
//	}
//
//
//
//	public void setActivityId(String activityId) {
//		this.activityId = activityId;
//	}



	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getBodyId() {
		return this.bodyId;
	}

	public void setBodyId(String bodyId) {
		this.bodyId = bodyId;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Double getPostedTime() {
		return this.postedTime;
	}

	public void setPostedTime(Double postedTime) {
		this.postedTime = postedTime;
	}

	public Double getPriority() {
		return this.priority;
	}

	public void setPriority(Double priority) {
		this.priority = priority;
	}

	public String getStreamFaviconUrl() {
		return this.streamFaviconUrl;
	}

	public void setStreamFaviconUrl(String streamFaviconUrl) {
		this.streamFaviconUrl = streamFaviconUrl;
	}

	public String getStreamSourceUrl() {
		return this.streamSourceUrl;
	}

	public void setStreamSourceUrl(String streamSourceUrl) {
		this.streamSourceUrl = streamSourceUrl;
	}

	public String getStreamTitle() {
		return this.streamTitle;
	}

	public void setStreamTitle(String streamTitle) {
		this.streamTitle = streamTitle;
	}

	public String getStreamUrl() {
		return this.streamUrl;
	}

	public void setStreamUrl(String streamUrl) {
		this.streamUrl = streamUrl;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitleId() {
		return this.titleId;
	}

	public void setTitleId(String titleId) {
		this.titleId = titleId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUserId() {
		return this.userId;
	}

	private void setUserId(String userId) {
		this.userId = userId;
	}

	

	public Person getPerson() {
		return person;
	}

//	public ActivityKey getActivityKey() {
//		return activityKey;
//	}
//
//
//
//	public void setActivityKey(ActivityKey activityKey) {
//		this.activityKey = activityKey;
//	}



	public void setPerson(Person person) {
		this.person = person;
	}



//	public Set<ActivityMediaItem> getMediaItems() {
//		return mediaItems;
//	}
//
//
//
//	public void setMediaItems(Set<ActivityMediaItem> mediaItems) {
//		this.mediaItems = mediaItems;
//	}
//
//
//
//	public Set<ActivityTemplateParam> getTemplateParams() {
//		return templateParams;
//	}
//
//
//
//	public void setTemplateParams(Set<ActivityTemplateParam> templateParams) {
//		this.templateParams = templateParams;
//	}


}
