package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * ActivityTemplateParam generated by hbm2java
 */
public class ActivityTemplateParam implements java.io.Serializable {

	private Integer id;
	private String paramKey;
	private String paramValue;
	private String activityId;
	private String userId;
	//private Activity activity;

	public ActivityTemplateParam() {
	}


//	public ActivityTemplateParam(String paramKey, String paramValue,
//			//int activityId) {
//			Activity activity){
//		this.paramKey = paramKey;
//		this.paramValue = paramValue;
//		this.activity = activity;
//	}

	public Integer getId() {
		return this.id;
	}

	private void setId(Integer id) {
		this.id = id;
	}

	public String getParamKey() {
		return this.paramKey;
	}

	public void setParamKey(String paramKey) {
		this.paramKey = paramKey;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}


//	public Activity getActivity() {
//		return activity;
//	}
//
//	public void setActivity(Activity activity) {
//		this.activity = activity;
//	}

	public String getActivityId() {
		return activityId;
	}


	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}


	public String getUserId() {
		return userId;
	}


	public void setUserId(String userId) {
		this.userId = userId;
	}

	
	
}
