package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * ActivityMediaItem generated by hbm2java
 */
public class ActivityMediaItem implements java.io.Serializable {

	private Integer id;
	private String mimeType;
	//private String type;
	private ItemTypeEnum type;
	private String url;
	private String thumbnailUrl;
	private String activityId;
	private String userId;
	//private Activity activity;

	public ActivityMediaItem() {
	}

	/*public ActivityMediaItem(int activityId) {
		this.activityId = activityId;
	}*/

	/*public ActivityMediaItem(String mimeType, String type, String url,
			//String thumbnailUrl, int activityId) {
			String thumbnailUrl, Activity activity) {
		this.mimeType = mimeType;
		this.type = type;
		this.url = url;
		this.thumbnailUrl = thumbnailUrl;
		//this.activityId = activityId;
		this.activity = activity;
	}*/

	public Integer getId() {
		return this.id;
	}

	private void setId(Integer id) {
		this.id = id;
	}

	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public ItemTypeEnum getType() {
		return this.type;
	}

	public void setType(ItemTypeEnum type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getThumbnailUrl() {
		return this.thumbnailUrl;
	}

	public void setThumbnailUrl(String thumbnailUrl) {
		this.thumbnailUrl = thumbnailUrl;
	}

//	public Activity getActivity() {
//		return activity;
//	}
//
//	public void setActivity(Activity activity) {
//		this.activity = activity;
//	}

	public String getActivityId() {
		return activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	

}
