package com.skt.opensocial.persistence;

import java.util.Set;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * PersonAdditionalInfo1 generated by hbm2java
 */
public class PersonAdditionalInfo1 implements java.io.Serializable {

	private Integer id;
	private String userId;
	private Info1AttributeEnum attribute;
	private String value;
	private Person person;
	
	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public PersonAdditionalInfo1() {
	}

	/*public PersonAdditionalInfo1(String userId) {
		this.userId = userId;
	}

	public PersonAdditionalInfo1(String userId, String attribute, String value) {
		this.userId = userId;
		this.attribute = attribute;
		this.value = value;
	}*/

	public Integer getId() {
		return this.id;
	}

	private void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Info1AttributeEnum getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Info1AttributeEnum attribute) {
		this.attribute = attribute;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
