package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {
	

	private String id;
	private User user;
	private Date updated;
	private String aboutme;
	private Integer age;
	private Date birthday;
	private String bodytypeBuild;
	private String bodytypeEyecolor;
	private String bodytypeHaircolor;
	private Double bodytypeHeight;
	private Double bodytypeWeight;
	private String children;
	private String currentlocationCountry;
	private Double currentlocationLatitude;
	private Double currentlocationLongitude;
	private String currentlocationLocality;
	private String currentlocationPostalcode;
	private String currentlocationRegion;
	private String currentlocationStreetaddress;
	private String currentlocationType;
	private String currentlocationFormatted;
	private Boolean currentlocationPrimary;
	private String displayname;
	//private String drinker;
	private DrinkerEnum drinker;
	private String ethnicity;
	private String fashion;
	//private String gender;
	private GenderEnum gender;
	private String happiestwhen;
	private Boolean hasapp;
	private String humor;
	private String jobinterests;
	private String livingarrangement;
	private String nameAdditionalname;
	private String nameFamilyname;
	private String nameGivenname;
	private String nameHonorificprefix;
	private String nameHonorificsuffix;
	private String nameFormatted;
	//private String networkpresence;
	private NetworkpresenceEnum networkpresence;
	private String nickname;
	private String pets;
	private String politicalviews;
	private String preferredusername;
	private String relationshipstatus;
	private String religion;
	private String romance;
	private String scaredof;
	private String sexualorientation;
	//private String smoker;
	private SmokerEnum smoker;
	private String status;
	private Double utcoffset;
	private String profilesongurlValue;
	private String profilesongurlLinkText;
	private String profilesongurlType;
	private Boolean profilesongurlPrimary;
	private String profilevideourlValue;
	private String profilevideourlLinkText;
	private String profilevideourlType;
	private Boolean profilevideourlPrimary;
	private String profilesongurl;
	private String profilevideourl;
	private String profileurl;
	private String thumbnailurl;
	private Set<PersonAdditionalInfo1> additionalInfo1s;
	private Set<PersonAdditionalInfo2> additionalInfo2s;
	private Set<PersonAccount> accounts;
	private Set<Address> addresses;
	private Set<PersonOrganization> organizations;
	private Set<Activity> activities = new HashSet<Activity>();
	private Set<PersonAppData> appData;
	private Set<PersonUrl> urls;

	public Person() {
	}

//	public Person(String id) {
//		this.id = id;
//	}

//	public Person(String id, Date updated, String aboutme, Integer age,
//			Date birthday, String bodytypeBuild, String bodytypeEyecolor,
//			String bodytypeHaircolor, Double bodytypeHeight,
//			Double bodytypeWeight, String children,
//			String currentlocationCountry, Double currentlocationLatitude,
//			Double currentlocationLongitude, String currentlocationLocality,
//			String currentlocationPostalcode, String currentlocationRegion,
//			String currentlocationStreetaddress, String currentlocationType,
//			String currentlocationFormatted, Boolean currentlocationPrimary,
//			//String displayname, String drinker, String ethnicity,
//			String displayname, DrinkerEnum drinker, String ethnicity,
//			//String fashion, String gender, String happiestwhen, Boolean hasapp,
//			String fashion, GenderEnum gender, String happiestwhen, Boolean hasapp,
//			String humor, String jobinterests, String livingarrangement,
//			String nameAdditionalname, String nameFamilyname,
//			String nameGivenname, String nameHonorificprefix,
//			String nameHonorificsuffix, String nameFormatted,
//			//String networkpresence, String nickname, String pets,
//			NetworkpresenceEnum networkpresence, String nickname, String pets,
//			String politicalviews, String preferredusername,
//			String relationshipstatus, String religion, String romance,
//			//String scaredof, String sexualorientation, String smoker,
//			String scaredof, String sexualorientation, SmokerEnum smoker,
//			String status, Double utcoffset, String profilesongurlValue,
//			String profilesongurlLinkText, String profilesongurlType,
//			String profilesongurlPrimary, String profilevideourlValue,
//			String profilevideourlLinkText, String profilevideourlType,
//			String profilevideourlPrimary, String profilesongurl,
//			String profilevideourl, String profileurl, String thumbnailurl) {
//		this.id = id;
//		this.updated = updated;
//		this.aboutme = aboutme;
//		this.age = age;
//		this.birthday = birthday;
//		this.bodytypeBuild = bodytypeBuild;
//		this.bodytypeEyecolor = bodytypeEyecolor;
//		this.bodytypeHaircolor = bodytypeHaircolor;
//		this.bodytypeHeight = bodytypeHeight;
//		this.bodytypeWeight = bodytypeWeight;
//		this.children = children;
//		this.currentlocationCountry = currentlocationCountry;
//		this.currentlocationLatitude = currentlocationLatitude;
//		this.currentlocationLongitude = currentlocationLongitude;
//		this.currentlocationLocality = currentlocationLocality;
//		this.currentlocationPostalcode = currentlocationPostalcode;
//		this.currentlocationRegion = currentlocationRegion;
//		this.currentlocationStreetaddress = currentlocationStreetaddress;
//		this.currentlocationType = currentlocationType;
//		this.currentlocationFormatted = currentlocationFormatted;
//		this.currentlocationPrimary = currentlocationPrimary;
//		this.displayname = displayname;
//		this.drinker = drinker;
//		this.ethnicity = ethnicity;
//		this.fashion = fashion;
//		this.gender = gender;
//		this.happiestwhen = happiestwhen;
//		this.hasapp = hasapp;
//		this.humor = humor;
//		this.jobinterests = jobinterests;
//		this.livingarrangement = livingarrangement;
//		this.nameAdditionalname = nameAdditionalname;
//		this.nameFamilyname = nameFamilyname;
//		this.nameGivenname = nameGivenname;
//		this.nameHonorificprefix = nameHonorificprefix;
//		this.nameHonorificsuffix = nameHonorificsuffix;
//		this.nameFormatted = nameFormatted;
//		this.networkpresence = networkpresence;
//		this.nickname = nickname;
//		this.pets = pets;
//		this.politicalviews = politicalviews;
//		this.preferredusername = preferredusername;
//		this.relationshipstatus = relationshipstatus;
//		this.religion = religion;
//		this.romance = romance;
//		this.scaredof = scaredof;
//		this.sexualorientation = sexualorientation;
//		this.smoker = smoker;
//		this.status = status;
//		this.utcoffset = utcoffset;
//		this.profilesongurlValue = profilesongurlValue;
//		this.profilesongurlLinkText = profilesongurlLinkText;
//		this.profilesongurlType = profilesongurlType;
//		this.profilesongurlPrimary = profilesongurlPrimary;
//		this.profilevideourlValue = profilevideourlValue;
//		this.profilevideourlLinkText = profilevideourlLinkText;
//		this.profilevideourlType = profilevideourlType;
//		this.profilevideourlPrimary = profilevideourlPrimary;
//		this.profilesongurl = profilesongurl;
//		this.profilevideourl = profilevideourl;
//		this.profileurl = profileurl;
//		this.thumbnailurl = thumbnailurl;
//	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public String getAboutme() {
		return this.aboutme;
	}

	public void setAboutme(String aboutme) {
		this.aboutme = aboutme;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getBodytypeBuild() {
		return this.bodytypeBuild;
	}

	public void setBodytypeBuild(String bodytypeBuild) {
		this.bodytypeBuild = bodytypeBuild;
	}

	public String getBodytypeEyecolor() {
		return this.bodytypeEyecolor;
	}

	public void setBodytypeEyecolor(String bodytypeEyecolor) {
		this.bodytypeEyecolor = bodytypeEyecolor;
	}

	public String getBodytypeHaircolor() {
		return this.bodytypeHaircolor;
	}

	public void setBodytypeHaircolor(String bodytypeHaircolor) {
		this.bodytypeHaircolor = bodytypeHaircolor;
	}

	public Double getBodytypeHeight() {
		return this.bodytypeHeight;
	}

	public void setBodytypeHeight(Double bodytypeHeight) {
		this.bodytypeHeight = bodytypeHeight;
	}

	public Double getBodytypeWeight() {
		return this.bodytypeWeight;
	}

	public void setBodytypeWeight(Double bodytypeWeight) {
		this.bodytypeWeight = bodytypeWeight;
	}

	public String getChildren() {
		return this.children;
	}

	public void setChildren(String children) {
		this.children = children;
	}

	public String getCurrentlocationCountry() {
		return this.currentlocationCountry;
	}

	public void setCurrentlocationCountry(String currentlocationCountry) {
		this.currentlocationCountry = currentlocationCountry;
	}

	public Double getCurrentlocationLatitude() {
		return this.currentlocationLatitude;
	}

	public void setCurrentlocationLatitude(Double currentlocationLatitude) {
		this.currentlocationLatitude = currentlocationLatitude;
	}

	public Double getCurrentlocationLongitude() {
		return this.currentlocationLongitude;
	}

	public void setCurrentlocationLongitude(Double currentlocationLongitude) {
		this.currentlocationLongitude = currentlocationLongitude;
	}

	public String getCurrentlocationLocality() {
		return this.currentlocationLocality;
	}

	public void setCurrentlocationLocality(String currentlocationLocality) {
		this.currentlocationLocality = currentlocationLocality;
	}

	public String getCurrentlocationPostalcode() {
		return this.currentlocationPostalcode;
	}

	public void setCurrentlocationPostalcode(String currentlocationPostalcode) {
		this.currentlocationPostalcode = currentlocationPostalcode;
	}

	public String getCurrentlocationRegion() {
		return this.currentlocationRegion;
	}

	public void setCurrentlocationRegion(String currentlocationRegion) {
		this.currentlocationRegion = currentlocationRegion;
	}

	public String getCurrentlocationStreetaddress() {
		return this.currentlocationStreetaddress;
	}

	public void setCurrentlocationStreetaddress(
			String currentlocationStreetaddress) {
		this.currentlocationStreetaddress = currentlocationStreetaddress;
	}

	public String getCurrentlocationType() {
		return this.currentlocationType;
	}

	public void setCurrentlocationType(String currentlocationType) {
		this.currentlocationType = currentlocationType;
	}

	public String getCurrentlocationFormatted() {
		return this.currentlocationFormatted;
	}

	public void setCurrentlocationFormatted(String currentlocationFormatted) {
		this.currentlocationFormatted = currentlocationFormatted;
	}

	public Boolean getCurrentlocationPrimary() {
		return this.currentlocationPrimary;
	}

	public void setCurrentlocationPrimary(Boolean currentlocationPrimary) {
		this.currentlocationPrimary = currentlocationPrimary;
	}

	public String getDisplayname() {
		return this.displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

//	public String getDrinker() {
//		return this.drinker;
//	}
//
//	public void setDrinker(String drinker) {
//		this.drinker = drinker;
//	}
	public DrinkerEnum getDrinker() {
		return drinker;
	}

	public void setDrinker(DrinkerEnum drinker) {
		this.drinker = drinker;
	}
	
	public String getEthnicity() {
		return this.ethnicity;
	}

	

	public void setEthnicity(String ethnicity) {
		this.ethnicity = ethnicity;
	}

	public String getFashion() {
		return this.fashion;
	}

	public void setFashion(String fashion) {
		this.fashion = fashion;
	}

	/*public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}*/

	
	public GenderEnum getGender() {
		return gender;
	}

	public void setGender(GenderEnum gender) {
		this.gender = gender;
	}
	
	public String getHappiestwhen() {
		return this.happiestwhen;
	}

	public void setHappiestwhen(String happiestwhen) {
		this.happiestwhen = happiestwhen;
	}

	public Boolean getHasapp() {
		return this.hasapp;
	}

	public void setHasapp(Boolean hasapp) {
		this.hasapp = hasapp;
	}

	public String getHumor() {
		return this.humor;
	}

	public void setHumor(String humor) {
		this.humor = humor;
	}

	public String getJobinterests() {
		return this.jobinterests;
	}

	public void setJobinterests(String jobinterests) {
		this.jobinterests = jobinterests;
	}

	public String getLivingarrangement() {
		return this.livingarrangement;
	}

	public void setLivingarrangement(String livingarrangement) {
		this.livingarrangement = livingarrangement;
	}

	public String getNameAdditionalname() {
		return this.nameAdditionalname;
	}

	public void setNameAdditionalname(String nameAdditionalname) {
		this.nameAdditionalname = nameAdditionalname;
	}

	public String getNameFamilyname() {
		return this.nameFamilyname;
	}

	public void setNameFamilyname(String nameFamilyname) {
		this.nameFamilyname = nameFamilyname;
	}

	public String getNameGivenname() {
		return this.nameGivenname;
	}

	public void setNameGivenname(String nameGivenname) {
		this.nameGivenname = nameGivenname;
	}

	public String getNameHonorificprefix() {
		return this.nameHonorificprefix;
	}

	public void setNameHonorificprefix(String nameHonorificprefix) {
		this.nameHonorificprefix = nameHonorificprefix;
	}

	public String getNameHonorificsuffix() {
		return this.nameHonorificsuffix;
	}

	public void setNameHonorificsuffix(String nameHonorificsuffix) {
		this.nameHonorificsuffix = nameHonorificsuffix;
	}

	public String getNameFormatted() {
		return this.nameFormatted;
	}
	
	public String getName(){
		return getNameFormatted();
	}

	public void setNameFormatted(String nameFormatted) {
		this.nameFormatted = nameFormatted;
	}

	public void setName(String name) {
		setNameFormatted(name);
	}
	/*public String getNetworkpresence() {
		return this.networkpresence;
	}

	public void setNetworkpresence(String networkpresence) {
		this.networkpresence = networkpresence;
	}*/

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPets() {
		return this.pets;
	}

	public void setPets(String pets) {
		this.pets = pets;
	}

	public String getPoliticalviews() {
		return this.politicalviews;
	}

	public void setPoliticalviews(String politicalviews) {
		this.politicalviews = politicalviews;
	}

	public String getPreferredusername() {
		return this.preferredusername;
	}

	public void setPreferredusername(String preferredusername) {
		this.preferredusername = preferredusername;
	}

	public String getRelationshipstatus() {
		return this.relationshipstatus;
	}

	public void setRelationshipstatus(String relationshipstatus) {
		this.relationshipstatus = relationshipstatus;
	}

	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	public String getRomance() {
		return this.romance;
	}

	public void setRomance(String romance) {
		this.romance = romance;
	}

	public String getScaredof() {
		return this.scaredof;
	}

	public void setScaredof(String scaredof) {
		this.scaredof = scaredof;
	}

	public String getSexualorientation() {
		return this.sexualorientation;
	}

	public void setSexualorientation(String sexualorientation) {
		this.sexualorientation = sexualorientation;
	}

	/*public String getSmoker() {
		return this.smoker;
	}

	public void setSmoker(String smoker) {
		this.smoker = smoker;
	}*/
	
	

	public String getStatus() {
		return this.status;
	}

	public NetworkpresenceEnum getNetworkpresence() {
		return networkpresence;
	}

	public void setNetworkpresence(NetworkpresenceEnum networkpresence) {
		this.networkpresence = networkpresence;
	}

	public SmokerEnum getSmoker() {
		return smoker;
	}

	public void setSmoker(SmokerEnum smoker) {
		this.smoker = smoker;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Double getUtcoffset() {
		return this.utcoffset;
	}

	public void setUtcoffset(Double utcoffset) {
		this.utcoffset = utcoffset;
	}

	public String getProfilesongurlValue() {
		return this.profilesongurlValue;
	}

	public void setProfilesongurlValue(String profilesongurlValue) {
		this.profilesongurlValue = profilesongurlValue;
	}

	public String getProfilesongurlLinkText() {
		return this.profilesongurlLinkText;
	}

	public void setProfilesongurlLinkText(String profilesongurlLinkText) {
		this.profilesongurlLinkText = profilesongurlLinkText;
	}

	public String getProfilesongurlType() {
		return this.profilesongurlType;
	}

	public void setProfilesongurlType(String profilesongurlType) {
		this.profilesongurlType = profilesongurlType;
	}

	

	public String getProfilevideourlValue() {
		return this.profilevideourlValue;
	}

	public void setProfilevideourlValue(String profilevideourlValue) {
		this.profilevideourlValue = profilevideourlValue;
	}

	public String getProfilevideourlLinkText() {
		return this.profilevideourlLinkText;
	}

	public void setProfilevideourlLinkText(String profilevideourlLinkText) {
		this.profilevideourlLinkText = profilevideourlLinkText;
	}

	public String getProfilevideourlType() {
		return this.profilevideourlType;
	}

	public void setProfilevideourlType(String profilevideourlType) {
		this.profilevideourlType = profilevideourlType;
	}

	

	public Boolean getProfilesongurlPrimary() {
		return profilesongurlPrimary;
	}

	public void setProfilesongurlPrimary(Boolean profilesongurlPrimary) {
		this.profilesongurlPrimary = profilesongurlPrimary;
	}

	public Boolean getProfilevideourlPrimary() {
		return profilevideourlPrimary;
	}

	public void setProfilevideourlPrimary(Boolean profilevideourlPrimary) {
		this.profilevideourlPrimary = profilevideourlPrimary;
	}

	public String getProfilesongurl() {
		return this.profilesongurl;
	}

	public void setProfilesongurl(String profilesongurl) {
		this.profilesongurl = profilesongurl;
	}

	public String getProfilevideourl() {
		return this.profilevideourl;
	}

	public void setProfilevideourl(String profilevideourl) {
		this.profilevideourl = profilevideourl;
	}

	public String getProfileurl() {
		return this.profileurl;
	}

	public void setProfileurl(String profileurl) {
		this.profileurl = profileurl;
	}

	public String getThumbnailurl() {
		return this.thumbnailurl;
	}

	public void setThumbnailurl(String thumbnailurl) {
		this.thumbnailurl = thumbnailurl;
	}

	public Set<PersonAdditionalInfo1> getAdditionalInfo1s() {
		return additionalInfo1s;
	}

	public void setAdditionalInfo1s(Set<PersonAdditionalInfo1> additionalInfo1s) {
		this.additionalInfo1s = additionalInfo1s;
	}

	public Set<PersonAdditionalInfo2> getAdditionalInfo2s() {
		return additionalInfo2s;
	}

	public void setAdditionalInfo2s(Set<PersonAdditionalInfo2> additionalInfo2s) {
		this.additionalInfo2s = additionalInfo2s;
	}

	public Set<PersonAccount> getAccounts() {
		return accounts;
	}

	public void setAccounts(Set<PersonAccount> accounts) {
		this.accounts = accounts;
	}

	public Set<Address> getAddresses() {
		return addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	public Set<PersonOrganization> getOrganizations() {
		return organizations;
	}

	public void setOrganizations(Set<PersonOrganization> organizations) {
		this.organizations = organizations;
	}

	public Set<Activity> getActivities() {
		return activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}
	
	public void addActivity(Activity activity){
		Set<Activity> set = getActivities();
		//activity.setUserId(this.id);
		set.add(activity);
		setActivities(set);
	}

	public Set<PersonAppData> getAppData() {
		return appData;
	}

	public void setAppData(Set<PersonAppData> appData) {
		this.appData = appData;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set<PersonUrl> getUrls() {
		return urls;
	}

	public void setUrls(Set<PersonUrl> urls) {
		this.urls = urls;
	}

}
