package com.skt.opensocial.persistence;

import java.util.Set;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * PersonAdditionalInfo1 generated by hbm2java
 */
public class PersonUrl implements java.io.Serializable {

	private int id;
	private Person person;
	private String value;
	private String linkText;
	private String type;
	private boolean primary;
	public int getId() {
		return id;
	}
	private void setId(int id) {
		this.id = id;
	}
	public Person getPerson() {
		return person;
	}
	public void setPerson(Person person) {
		this.person = person;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	public String getLinkText() {
		return linkText;
	}
	public void setLinkText(String linkText) {
		this.linkText = linkText;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public boolean isPrimary() {
		return getPrimary();
	}
	public boolean getPrimary(){
		return primary;
	}
	public void setPrimary(boolean primary) {
		this.primary = primary;
	}

}
