package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * FavoriteGadget generated by hbm2java
 */
public class FavoriteGadget implements java.io.Serializable {

	private Long id;
	private String userId;
	private long gadgetId;

	public FavoriteGadget() {
	}

	public FavoriteGadget(String userId, long gadgetId) {
		this.userId = userId;
		this.gadgetId = gadgetId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public long getGadgetId() {
		return this.gadgetId;
	}

	public void setGadgetId(long gadgetId) {
		this.gadgetId = gadgetId;
	}

}
