package com.skt.opensocial.persistence;

// Generated Jun 25, 2009 4:34:44 PM by Hibernate Tools 3.2.4.GA

/**
 * Friends generated by hbm2java
 */
public class Friends implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String friendId;

	public Friends() {
	}

	public Friends(String userId, String friendId) {
		this.userId = userId;
		this.friendId = friendId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFriendId() {
		return this.friendId;
	}

	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}

}
